service: micro-graphql-pricing

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

functions:
  app:
    handler: index.handler
    # Add the following lines:
    events:
      - http:
          path: graphql
          method: any
